[project]
name = "mhctl"
version = "0.0.1"
dependencies = [
    "typer",
    "yamlium",
    "pathlib",
    "httpx",
    "xxhash"
]
requires-python = ">= 3.9"
[project.optional-dependencies]
function1 = []
function2 = []

[project.scripts]
mhctl = "mhctl.cli:app"
