[project]
name = "mhctl"
version = "0.0.1"
dependencies = [
    "typer",
    "yamlium"
]
requires-python = ">= 3.8"
[project.optional-dependencies]
function1 = []
function2 = []

[project.scripts]
mhctl = "mhctl.cli:app"
