name: Build mhctl

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install nuitka httpx xxhash typer yamlium
      - name: Build
        run: |
          python -m nuitka \
            --onefile \
            --lto=no \
            --enable-plugin=anti-bloat \
            --python-flag=-O \
            --include-package=mhctl \
            --include-package-data=mhctl \
            --output-dir=build \
            --output-filename=mhctl \
            --jobs=4 \
            --remove-output \
            --follow-imports \
            --module-parameter=use-stdlib-static-typing=no \
            mhctl/__main__.py
      - name: Rename dist folder
        run: mv build/mhctl.dist mhctl.dist
      - name: Copy data
        run: |
          cp -r mhctl/config build/
          cp -r mhctl/data build/
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mhctl-linux
          path: mhctl.dist

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install nuitka httpx xxhash typer yamlium
      - name: Build
        run: |
          python -m nuitka `
            --onefile `
            --lto=no `
            --enable-plugin=anti-bloat `
            --python-flag=-O `
            --include-package=mhctl `
            --include-package-data=mhctl `
            --output-dir=build `
            --output-filename=mhctl.exe `
            --jobs=4 `
            --remove-output `
            --follow-imports `
            mhctl/__main__.py
      - name: Rename dist folder
        run: Move-Item -Path build/mhctl.dist -Destination mhctl.dist
      - name: Copy data
        run: |
          Copy-Item -Recurse -Force mhctl\config mhctl.dist\config
          Copy-Item -Recurse -Force mhctl\data mhctl.dist\data
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mhctl-windows
          path: mhctl.dist